export default {
    category: ['bag', 'backpack', 'belt', 'blouse', 'boots', 'briefcase', 'canvas', 'cap', 'cardigan', 'chinos', 'coat', 'dress', 'dress Shirt',
        'dress shoes', 'dolphin shorts', 'earring', 'footwear', 'glove', 'ground jumper', 'gown', 'high-heel', 'hoody', 'jacket', 'jean', 'jumper', 'leggings',
        'messenger bag', 'muffler', 'mustang', 'necklace', 'necktie', 'onepiece dress', 'outdoor', 'pants', 'purse', 'rider jacket', 'ring',
        'scarf', 'shorts', 'skinny Jean', 'skirt', 'slacks', 'slip on', 'slipper', 'sneakers', 'sunglasses', 'sports wear', 'sweater', 'tailored Jacket',
        'turtle Neck', 'trousers', 'vest', 'wallet', 'watch', 'windbreaker'
    ],
    brand: ['GUCCI', 'HERMES', 'LOUIS VUITTON', 'CHANEL', 'PRADA', 'GIVENCHY', 'ROLEX', 'CELINE', 'SAINT LAURENT','MARNI'],
    tag: ['spring', 'summer', 'fall', 'winter', 'limited edition',
        'luxurious', 'vintage', 'sleeveless', 'lace', 'see-through', 'stripe', 'dotted', 'pattern'
    ],
    state: ['상', '중', '하'],
    status: ['대여 가능', '대여 중', '판매 완료', '세탁 중', '배송 중', '수리 중'],
    nation: ['대한민국', '이탈리아', '일본', '호주', '영국', '미국', '프랑스', '중국', '독일', '인도'],
    color: ['Beige', 'Black', 'Blue', 'Brown', 'Charcoal', 'Gray', 'Green',
        'Indigo', 'Khaki', 'Light Pink', 'Lime', 'Olive', 'Orange', "Pink", 'Red', 'Sky', 'White', 'Yellow'
    ],
    //     color: [{ 'color': 'Beige', 'url': 'beige.png' },
    //     { 'color': 'Black', 'url': 'black.png' },
    //     { 'color': 'Blue', 'url': 'blue.png' },
    //     { 'color': 'Brown', 'url': 'brown.png' },
    //     { 'color': 'Charcoal', 'url': 'charcoal.png' },
    //     { 'color': 'Gray', 'url': 'gray.png' },
    //     { 'color': 'Green', 'url': 'green.png' },
    //     { 'color': 'Indigo', 'url': 'indigo.png' },
    //     { 'color': 'Khaki', 'url': 'khaki.png' },
    //     { 'color': 'Light Pink', 'url': 'light_pink.png' },
    //     { 'color': 'Lime', 'url': 'lime.png' },
    //     { 'color': 'Olive', 'url': 'olive.png' },
    //     { 'color': 'Orange', 'url': 'orange.png' },
    //     { 'color': 'Pink', 'url': 'pink.png' },
    //     { 'color': 'Red', 'url': 'red.png' },
    //     { 'color': 'Sky', 'url': 'sky.png' },
    //     { 'color': 'White', 'url': 'white.png' },
    //     { 'color': 'Yellow', 'url': 'yellow.png' },
    // ]
}